
import { Language, Discipline, Status, RiskLevel, Task } from './types';
import { addDays, format } from 'date-fns';

export const TRANSLATIONS = {
  [Language.English]: {
    title: "BIROUK ULTIMATE 3WLA ENGINE v2025",
    subtitle: "Orchestrated by Madame Salima BIROUK",
    dashboard: "Dashboard",
    schedule: "3WLA Schedule",
    hse: "HSE & Permits",
    reports: "Reports & Export",
    week: "Week",
    discipline: "Discipline",
    activity: "Activity / WBS",
    status: "Status",
    mri: "MRI %",
    manpower: "Manpower",
    risk: "Risk Level",
    generate: "Generate Executive Plan",
    exportPdf: "Export PDF",
    exportXlsx: "Export Excel",
    exportXer: "Export XER",
    exportPbix: "Export PowerBI",
    welcome: "System Ready. Select Language.",
    hseCompliance: "HSE Compliance",
    materials: "Material Readiness",
    manpowerHistogram: "Manpower Histogram",
    executiveSummary: "Executive Summary",
    generatedBy: "Generated for Madame Salima BIROUK",
    riskAnalysis: "AI Risk Analysis",
    weather: "Weather Impact",
    constraints: "Constraints Log",
    simops: "SIMOPS Detected",
    jha: "JHA",
    ptw: "PTW",
    confirmed: "Confirmed",
    pending: "Pending",
    // New Actions
    addTask: "Add New Activity",
    editTask: "Edit Activity",
    save: "Save Changes",
    cancel: "Cancel",
    delete: "Delete",
    description: "Description",
    dates: "Start / End Date",
    progress: "Progress %",
    comments: "Daily Report / Comments",
    actions: "Actions"
  },
  [Language.French]: {
    title: "MOTEUR BIROUK ULTIMATE 3WLA v2025",
    subtitle: "Orchestré par Madame Salima BIROUK",
    dashboard: "Tableau de Bord",
    schedule: "Planning 3WLA",
    hse: "HSE & Permis",
    reports: "Rapports & Export",
    week: "Semaine",
    discipline: "Discipline",
    activity: "Activité / WBS",
    status: "Statut",
    mri: "MRI %",
    manpower: "Main d'œuvre",
    risk: "Niveau de Risque",
    generate: "Générer Plan Exécutif",
    exportPdf: "Exporter PDF",
    exportXlsx: "Exporter Excel",
    exportXer: "Exporter XER",
    exportPbix: "Exporter PowerBI",
    welcome: "Système Prêt. Choisissez la langue.",
    hseCompliance: "Conformité HSE",
    materials: "Disponibilité Matériel",
    manpowerHistogram: "Histogramme Main d'œuvre",
    executiveSummary: "Synthèse Exécutive",
    generatedBy: "Généré pour Madame Salima BIROUK",
    riskAnalysis: "Analyse de Risque IA",
    weather: "Impact Météo",
    constraints: "Registre des Contraintes",
    simops: "SIMOPS Détectés",
    jha: "JHA",
    ptw: "PT de Travail",
    confirmed: "Confirmé",
    pending: "En Attente",
    // New Actions
    addTask: "Ajouter Activité",
    editTask: "Modifier Activité",
    save: "Enregistrer",
    cancel: "Annuler",
    delete: "Supprimer",
    description: "Description",
    dates: "Date Début / Fin",
    progress: "Avancement %",
    comments: "Rapport Journalier / Commentaires",
    actions: "Actions"
  },
  [Language.Arabic]: {
    title: "محرك بيروك النهائي للجدولة v2025",
    subtitle: "تحت إشراف السيدة سليمة بيروك",
    dashboard: "لوحة القيادة",
    schedule: "الجدول الزمني 3 أسابيع",
    hse: "الصحة والسلامة والبيئة",
    reports: "التقارير والتصدير",
    week: "أسبوع",
    discipline: "التخصص",
    activity: "النشاط / WBS",
    status: "الحالة",
    mri: "مؤشر المواد %",
    manpower: "القوى العاملة",
    risk: "مستوى المخاطر",
    generate: "إنشاء الخطة التنفيذية",
    exportPdf: "تصدير PDF",
    exportXlsx: "تصدير Excel",
    exportXer: "تصدير XER",
    exportPbix: "تصدير PowerBI",
    welcome: "النظام جاهز. اختر اللغة.",
    hseCompliance: "الامتثال للسلامة",
    materials: "جاهزية المواد",
    manpowerHistogram: "مدرج القوى العاملة",
    executiveSummary: "الملخص التنفيذي",
    generatedBy: "تم الإنشاء للسيدة سليمة بيروك",
    riskAnalysis: "تحليل المخاطر بالذكاء الاصطناعي",
    weather: "تأثير الطقس",
    constraints: "سجل المعوقات",
    simops: "تداخل العمليات",
    jha: "تحليل المخاطر",
    ptw: "تصريح عمل",
    confirmed: "مؤكد",
    pending: "قيد الانتظار",
    // New Actions
    addTask: "إضافة نشاط جديد",
    editTask: "تعديل النشاط",
    save: "حفظ التغييرات",
    cancel: "إلغاء",
    delete: "حذف",
    description: "الوصف",
    dates: "تاريخ البدء / الانتهاء",
    progress: "التقدم %",
    comments: "التقرير اليومي / ملاحظات",
    actions: "إجراءات"
  },
  [Language.Spanish]: {
    title: "MOTOR BIROUK ULTIMATE 3WLA v2025",
    subtitle: "Orquestado por Madame Salima BIROUK",
    dashboard: "Panel de Control",
    schedule: "Cronograma 3WLA",
    hse: "HSE y Permisos",
    reports: "Informes y Exportación",
    week: "Semana",
    discipline: "Disciplina",
    activity: "Actividad / WBS",
    status: "Estado",
    mri: "MRI %",
    manpower: "Mano de Obra",
    risk: "Nivel de Riesgo",
    generate: "Generar Plan Ejecutivo",
    exportPdf: "Exportar PDF",
    exportXlsx: "Exportar Excel",
    exportXer: "Exportar XER",
    exportPbix: "Exportar PowerBI",
    welcome: "Sistema Listo. Seleccione Idioma.",
    hseCompliance: "Cumplimiento HSE",
    materials: "Disponibilidad Material",
    manpowerHistogram: "Histograma Mano de Obra",
    executiveSummary: "Resumen Ejecutivo",
    generatedBy: "Generado para Madame Salima BIROUK",
    riskAnalysis: "Análisis de Riesgo IA",
    weather: "Impacto Clima",
    constraints: "Registro de Restricciones",
    simops: "SIMOPS Detectados",
    jha: "AST",
    ptw: "Permiso",
    confirmed: "Confirmado",
    pending: "Pendiente",
    // New Actions
    addTask: "Añadir Actividad",
    editTask: "Editar Actividad",
    save: "Guardar",
    cancel: "Cancelar",
    delete: "Eliminar",
    description: "Descripción",
    dates: "Fecha Inicio / Fin",
    progress: "Progreso %",
    comments: "Reporte Diario / Comentarios",
    actions: "Acciones"
  },
  [Language.German]: {
    title: "BIROUK ULTIMATE 3WLA MASCHINE v2025",
    subtitle: "Orchestrierte von Frau Salima BIROUK",
    dashboard: "Armaturenbrett",
    schedule: "3WLA Zeitplan",
    hse: "HSE & Genehmigungen",
    reports: "Berichte & Export",
    week: "Woche",
    discipline: "Disziplin",
    activity: "Aktivität / WBS",
    status: "Status",
    mri: "Material %",
    manpower: "Arbeitskraft",
    risk: "Risikostufe",
    generate: "Ausführungsplan Erstellen",
    exportPdf: "PDF Exportieren",
    exportXlsx: "Excel Exportieren",
    exportXer: "XER Exportieren",
    exportPbix: "PowerBI Exportieren",
    welcome: "System bereit. Sprache wählen.",
    hseCompliance: "HSE-Konformität",
    materials: "Materialverfügbarkeit",
    manpowerHistogram: "Personalhistogramm",
    executiveSummary: "Zusammenfassung",
    generatedBy: "Generiert für Frau Salima BIROUK",
    riskAnalysis: "KI-Risikoanalyse",
    weather: "Wettereinfluss",
    constraints: "Einschränkungsprotokoll",
    simops: "SIMOPS Erkannt",
    jha: "Gefährdungsbeurteilung",
    ptw: "Arbeitserlaubnis",
    confirmed: "Bestätigt",
    pending: "Ausstehend",
    // New Actions
    addTask: "Aktivität Hinzufügen",
    editTask: "Aktivität Bearbeiten",
    save: "Speichern",
    cancel: "Abbrechen",
    delete: "Löschen",
    description: "Beschreibung",
    dates: "Start / Enddatum",
    progress: "Fortschritt %",
    comments: "Tagesbericht / Kommentare",
    actions: "Aktionen"
  },
  [Language.Norwegian]: {
    title: "BIROUK ULTIMAT 3WLA MOTOR v2025",
    subtitle: "Orkestrert av Madame Salima BIROUK",
    dashboard: "Dashbord",
    schedule: "3WLA Tidsplan",
    hse: "HSE & Tillatelser",
    reports: "Rapporter & Eksport",
    week: "Uke",
    discipline: "Disiplin",
    activity: "Aktivitet / WBS",
    status: "Status",
    mri: "MRI %",
    manpower: "Arbeidskraft",
    risk: "Risikonivå",
    generate: "Generer Utførelsesplan",
    exportPdf: "Eksporter PDF",
    exportXlsx: "Eksporter Excel",
    exportXer: "Eksporter XER",
    exportPbix: "Eksporter PowerBI",
    welcome: "System klart. Velg språk.",
    hseCompliance: "HSE Samsvar",
    materials: "Materialtilgjengelighet",
    manpowerHistogram: "Bemanningshistogram",
    executiveSummary: "Sammendrag",
    generatedBy: "Generert for Madame Salima BIROUK",
    riskAnalysis: "AI Risikoanalyse",
    weather: "Værpåvirkning",
    constraints: "Begrensningslogg",
    simops: "SIMOPS Oppdaget",
    jha: "SJA",
    ptw: "Arbeidstillatelse",
    confirmed: "Bekreftet",
    pending: "Avventer",
    // New Actions
    addTask: "Legg til Aktivitet",
    editTask: "Rediger Aktivitet",
    save: "Lagre",
    cancel: "Avbryt",
    delete: "Slett",
    description: "Beskrivelse",
    dates: "Start / Sluttdato",
    progress: "Fremdrift %",
    comments: "Daglig Rapport / Kommentarer",
    actions: "Handlinger"
  }
};

const disciplines = Object.values(Discipline);
const statuses = Object.values(Status);

export const MOCK_TASKS: Task[] = Array.from({ length: 15 }).map((_, i) => {
  const disc = disciplines[i % disciplines.length];
  const stat = statuses[i % statuses.length];
  const riskVal = Math.random();
  const risk = riskVal > 0.85 ? RiskLevel.Critical : riskVal > 0.6 ? RiskLevel.High : riskVal > 0.3 ? RiskLevel.Medium : RiskLevel.Low;
  
  const today = new Date();
  const startOffset = Math.floor(Math.random() * 20) - 10;
  const duration = Math.floor(Math.random() * 10) + 2;
  const start = addDays(today, startOffset);
  const end = addDays(start, duration);

  return {
    id: `ACT-${2025000 + i}`,
    wbs: `WBS-0${(i % 5) + 1}.${i}`,
    description: `${disc} Installation - Area ${Math.floor(i / 10) + 1}`,
    discipline: disc,
    startDate: format(start, 'yyyy-MM-dd'),
    endDate: format(end, 'yyyy-MM-dd'),
    status: stat,
    progress: stat === Status.Completed ? 100 : stat === Status.Planned ? 0 : Math.floor(Math.random() * 90),
    manpower: Math.floor(Math.random() * 15) + 2,
    equipment: i % 3 === 0 ? ['Crane 50T'] : i % 5 === 0 ? ['Excavator'] : [],
    materialsStatus: Math.floor(Math.random() * 40) + 60,
    hseRisks: risk === RiskLevel.Critical ? ['Lifting > 50T', 'Height'] : [],
    jhaStatus: Math.random() > 0.3,
    ptwStatus: Math.random() > 0.4,
    riskLevel: risk,
    responsible: i % 2 === 0 ? 'Youssef B.' : 'Karim A.',
    delayCause: stat === Status.Delayed ? 'Material' : undefined,
    comments: "Daily target met."
  };
});
